FinancialPortal/Models/Viewmodels/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;

namespace FinancialPortal.Models.Viewmodels
{
    public class HomeViewModel : BaseViewModel
    {
        public Household Household { get; set; }
        public ICollection<BankAccountViewModel> BankAccounts { get; set; }
    }

    public class AccountBalanceEditor
    {
        [RegularExpression(@"^\-?\d+\.\d{0,2}$", ErrorMessage = "Must be a 2-digit decimal value.")]
        [Range(-999999999.99, 999999999.99, ErrorMessage = "Cannot exceed $1B in magnitude.")]
        [Display(Name = "Balance")]
        public decimal BankAccountBalance { get; set; }
    }

    public class BankAccountViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BankName { get; set; }
        public string AccountType { get; set; }
        public string Owner { get; set; }
        public string Balance { get; set; }
        public AccountBalanceEditor BalanceEditor { get; set; }
        public BankAccountDetailsViewModel Details { get; set; }
        public HashSet<TransactionViewModel> Transactions { get; set; }
        public CreateTransactionViewModel TransactionCreator { get; set; }
    }
}

FinancialPortal/Controllers/BankAccountsController.cs
using FinancialPortal.Models;
using FinancialPortal.Models.Attributes;
using FinancialPortal.Models.HelperModels;
using FinancialPortal.Models.Viewmodels;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static FinancialPortal.Models.Viewmodels.CreateBankAccountViewModel;

namespace FinancialPortal.Controllers
{
    [AuthorizeCustom]
    public class BankAccountsController : BaseController
    {
        public ActionResult Create()
        {
            CreateBankAccountViewModel vm = new CreateBankAccountViewModel
            {
                BankAccountTypeList = new Dictionary<int, string>(),
                BankNameList = new SelectList(db.BankNames.ToList(), "Id", "Name", null)
            };
            foreach (var type in db.BankAccountTypes.ToList())
            {
                vm.BankAccountTypeList.Add(type.Id, type.Name);
            }
            return View(vm);
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateBankAccountViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                foreach (var _type in db.BankAccountTypes.ToList())
                {
                    vm.BankAccountTypeList.Add(_type.Id, _type.Name);
                }
                vm.BankNameList = new SelectList(db.BankNames.ToList(), "Id", "Name", vm.BankNameSelection);
                return View(vm);
            }
            var nickname = (vm.NickName == null || string.IsNullOrWhiteSpace(vm.NickName)) ? "My Default Account" : vm.NickName;
            var type = db.BankAccountTypes.Find(vm.BankAccountTypeSelection);
            var house = db.Households.Find(User.Identity.GetHouseholdId());
            var user = db.Users.Find(User.Identity.GetUserId());
            var bankName = db.BankNames.Find(vm.BankNameSelection);
            var balance = vm.BankAccountBalance;
            var account = new BankAccount();
            account.NickName = nickname;
            account.BankNameId = bankName.Id;
            account.BankAccountTypeId = type.Id;
            account.OwnerId = user.Id;
            account.Balance = balance;
            db.BankAccounts.Add(account);
            AddAccountToHouseholdUsers(account);
            db.Entry(account).State = EntityState.Added;
            db.SaveChanges();
            await ControllerContext.HttpContext.RefreshAuthentication(user);
            return RedirectToAction("Index", "Home");
        }

        public void AddAccountToHouseholdUsers(BankAccount account)
        {
            foreach (var user in db.Households.Find(User.Identity.GetHouseholdId()).Members)
            {
                user.BankAccounts.Add(account);
                db.Entry(user).State = EntityState.Modified;
            }
        }

        [AuthBankAccount]
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                if (db.BankAccounts.Find(id) != null)
                {
                    var account = db.BankAccounts.Find(id);
                    var vm = new EditBankAccountViewModel(
                        db.BankNames.ToList(),
                        db.BankAccountTypes.ToList(),
                        account.BankNameId,
                        account.BankAccountTypeId
                        );
                    vm.NickName = account.NickName;
                    ViewBag.Id = account.Id;
                    return View(vm);
                }
            }
            return RedirectToAction("Index", "Home");
        }
        [AuthBankAccount]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditBankAccountViewModel vm, int? id)
        {
            if (id != null)
            {
                if (!ModelState.IsValid)
                {
                    vm.BankAccountTypeList = new SelectList(db.BankAccountTypes.ToList(), "Id", "Name", vm.BankAccountTypeSelection);
                    vm.BankNameList = new SelectList(db.BankNames.ToList(), "Id", "Name", vm.BankNameSelection);
                    return View(vm);
                }
                var account = db.BankAccounts.Find(id);
                if (account != null)
                {
                    account.NickName = vm.NickName;
                    account.BankNameId = vm.BankNameSelection;
                    account.BankAccountTypeId = vm.BankAccountTypeSelection;
                    db.Entry(account).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [AuthBankAccount]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (id != null)
            {
                var account = db.BankAccounts.Find(id);
                if (account != null)
                {
                    db.BankAccounts.Remove(account);
                    db.Entry(account).State = EntityState.Deleted;
                    user.BankAccounts.Remove(account);
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    await ControllerContext.HttpContext.RefreshAuthentication(user);
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewData["Test"] = "OMG";
            return Redirect(Request.UrlReferrer.ToString());
        }

        [AuthBankAccount]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBalance(int? id, AccountBalanceEditor vm)
        {
            if (id != null)
            {
                var account = db.BankAccounts.Find(id);
                if (account != null)
                {
                    if (!ModelState.IsValid)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    account.Balance = vm.BankAccountBalance;
                    db.Entry(account).State = EntityState.Modified;
                    db.SaveChanges();
                    ViewData["BalanceSuccess"] = "Your account balance was successfully updated";
                }
            }
            return RedirectToAction("Index", "Home");
        }

        //[HttpPost]
        //public ActionResult UpdateBalanceAjax(string )
        //{
        //    Dictionary<string, string> dictionary = new Dictionary<string, string>();
        //    MyObject request = JsonConvert.DeserializeObject<MyObject>(obj);
        //    var account = db.BankAccounts.Find(request.Id);
        //    if (account != null)
        //    {
        //        account.Balance = request.Value;
        //        db.Entry(account).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return Json(new { Message = "Good", JsonRequestBehavior.AllowGet });
        //    }
        //    return Json(new { Message = "Bad", JsonRequestBehavior.AllowGet });
        //}
        ////[HttpPost]
        ////[ValidateAntiForgeryToken]
        ////public ActionResult UpdateBalance()
        ////{
        ////}
        //public class MyObject
        //{
        //    [JsonProperty("Id")]
        //    public int Id { get; set; }
        //    [JsonProperty("Value")]
        //    public decimal Value { get; set; }
        //}
    }

}

FinancialPortal/Controllers/InvitesController.cs
using FinancialPortal.Models;
using FinancialPortal.Models.HelperModels;
using FinancialPortal.Models.Viewmodels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FinancialPortal.Controllers
{
    [Authorize]
    public class InvitesController : BaseController
    {
        public ActionResult Accept(int? id)
        {
            if (id != null)
            {
                AcceptViewModel vm = new AcceptViewModel();
                vm.Invite = db.Invites.Find(id);
                if (vm.Invite != null)
                {
                    var user = db.Users.Find(User.Identity.GetUserId());
                    if (user.Invites.Any(i => i.Id == vm.Invite.Id && i.Accepted == false && i.InviteeId == vm.Invite.InviteeId) && vm.Invite.InviteeId == user.Id && vm.Invite.Accepted == false)
                    {
                        vm.Household = db.Households.Find(vm.Invite.HouseholdId);
                        return View(vm);
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Accept")]
        public async Task<ActionResult> Accept(AcceptViewModel vm)
        {
            var invite = db.Invites.Find(vm.Invite.Id);
            var household = db.Households.Find(vm.Household.Id);
            if (invite != null && household != null)
            {
                if (db.Users.Find(User.Identity.GetUserId()).Invites.Any(i => i.Id == invite.Id) && invite.Accepted == false)
                {
                    invite.Accepted = true;
                    var invitee = db.Users.Find(invite.InviteeId);
                    if (invitee.HouseholdId != null)
                    {
                        db.Households.Find(invitee.HouseholdId).Members.Remove(invitee);
                    }
                    var alerts = invitee.Alerts.Where(a => a.InviteId == null ||
                    (a.Invite.Accepted == true && a.Invite.InviteeId == invitee.Id) ||
                    (a.Invite.Declined == true && a.Invite.InviteeId == invitee.Id));
                    db.Alerts.RemoveRange(alerts);
                    invitee.HouseholdId = invite.HouseholdId;
                    household.Members.Add(invitee);
                    invitee.Invites.Remove(invite);
                    db.Entry(invite).State = EntityState.Modified;
                    db.SaveChanges();
                    var members = household.Members.Where(m => m.Id != invitee.Id);
                    foreach (var member in members)
                    {
                        await AcceptAlert(member.Id, invitee.FullName, invite.Id);
                    }
                    await AcceptAlert(invitee.Id, invite.Id, invite.Inviter.FullName);
                    await ControllerContext.HttpContext.RefreshAuthentication(invitee);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Decline")]
        public async Task<ActionResult> Decline(AcceptViewModel vm)
        {
            var invite = db.Invites.Find(vm.Invite.Id);
            var household = db.Households.Find(vm.Household.Id);
            if (invite != null && household != null)
            {
                if (db.Users.Find(User.Identity.GetUserId()).Invites.Any(i => i.Id == invite.Id) && invite.Accepted == false)
                {
                    invite.Declined = true;
                    var invitee = db.Users.Find(invite.InviteeId);
                    invitee.Invites.Remove(invite);
                    var alerts = invitee.Alerts.Where(a => a.InviteId == null ||
                    (a.Invite.Accepted == true && a.Invite.InviteeId == invitee.Id) ||
                    (a.Invite.Declined == true && a.Invite.InviteeId == invitee.Id));
                    db.Alerts.RemoveRange(alerts);
                    db.Entry(invite).State = EntityState.Modified;
                    db.SaveChanges();
                    await DeclineAlert(invite.InviterId, invitee.FullName, invite.Id);
                    await ControllerContext.HttpContext.RefreshAuthentication(invitee);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Invite()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            InviteHouseholdViewModel vm = new InviteHouseholdViewModel();
            vm.InviteHouseholdId = user.Household.Id;
            var users = db.Users.Where(u =>
            !u.Invites.Any(i => i.Accepted == false && i.HouseholdId == user.HouseholdId)
            )
            .Where(u => u.HouseholdId != user.HouseholdId)
            .ToList();
            if (users.Count() > 0)
            {
                vm.UserList = new SelectList(users.OrderBy(u => u.LastName), "Id", "UserName", vm.UserId);
            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Invite(InviteHouseholdViewModel vm)
        {
            var invite = new Invite();
            invite.InviterId = User.Identity.GetUserId();
            invite.InviteeId = vm.UserId;
            invite.HouseholdId = vm.InviteHouseholdId;
            invite.Household = db.Households.Find(vm.HouseholdId);
            var invitee = db.Users.Find(invite.InviteeId);
            invitee.Invites.Add(invite);
            invite.InviteText = String.Format("{0} invited you to join their household.", db.Users.Find(invite.InviterId).FullName);
            db.SaveChanges();
            await InviteAlert(User.Identity.GetFullName(), invite.InviteeId, invite.Id);
            return RedirectToAction("Index", "Home");
        }

        public async Task InviteAlert(string inviterName, string inviteeId, int inviteId)
        {
            Alert alert = new Alert();
            alert.AlerteeId = inviteeId;
            alert.AlertText = String.Format("{0} invited you to join their household", inviterName);
            alert.InviteId = inviteId;
            db.Alerts.Add(alert);
            await db.SaveChangesAsync();
        }

        public async Task AcceptAlert(string inviterId, string inviteeName, int inviteId)
        {
            Alert alert = new Alert();
            alert.AlerteeId = inviterId;
            alert.AlertText = String.Format("{0} joined your household", inviteeName);
            alert.InviteId = inviteId;
            db.Alerts.Add(alert);
            await db.SaveChangesAsync();
        }

        public async Task AcceptAlert(string inviteeId, int inviteId, string inviterName)
        {
            Alert alert = new Alert();
            alert.AlerteeId = inviteeId;
            alert.AlertText = String.Format("You joined {0}'s household", inviterName);
            alert.InviteId = inviteId;
            db.Alerts.Add(alert);
            await db.SaveChangesAsync();
        }

        public async Task DeclineAlert(string inviterId, string inviteeName, int inviteId)
        {
            Alert alert = new Alert();
            alert.AlerteeId = inviterId;
            alert.AlertText = String.Format("{0} declined your invitation to join your household", inviteeName);
            alert.InviteId = inviteId;
            db.Alerts.Add(alert);
            await db.SaveChangesAsync();
        }
    }
}

FinancialPortal/Views/Home/Index.cshtml
@model FinancialPortal.Models.Viewmodels.HomeViewModel
@{
    ViewBag.Title = "Home";
}
@if (ViewData["Test"] != null)
{ <p>@ViewData["Test"].ToString()</p>}
<div class="row">
    <h3 class="text-center">Household</h3>
    <div class="col-sm-6 col-md-4">
        <h4>Household Name</h4>
        <p>@Model.Household.Name</p>
    </div>
    <div class="col-sm-6 col-md-4">
        <h4>Members</h4>
        <ol>
            @if (Model.Household.Members != null)
            {
                foreach (var member in Model.Household.Members)
                {
            <li>@member.FullName</li>
                }
            }
        </ol>
        @Html.ActionLink("Invite", "Invite", "Invites", null, new { @class = "btn btn-default" })
    </div>
    <div class="col-sm-6 col-md-4">
        <h4>Leave Household</h4>
        @using (Html.BeginForm("Leave", "Households", new { id = Model.Household.Id }, FormMethod.Post))
        {
        <input type="submit" role="button" value="Leave" class="btn btn-danger" />
        }
    </div>
</div>
<hr />
<h3 class="text-center">Accounts</h3>
<div class="row">

    <div class="col-lg-12">
        @if (Model.BankAccounts.Count() > 0)
        {
            foreach (var account in Model.BankAccounts)
            {
                <p>
                    @if (account.Name != null && !string.IsNullOrWhiteSpace(account.Name))
                    {
                        <text> @String.Format("{0} ({1})", account.Name, account.BankName)</text>
                    }
                    else
                    {
                        <text> @account.BankName</text>
                    }
                    <strong>@account.Balance</strong>
                    <div class="btn-group btn-group-sm" style="display:inline-block">
                        <a href="@Url.Action("Edit", "BankAccounts", new { id = account.Id } )" class="btn btn-default btn-xs">
                            Edit
                        </a>
                        <a href="#" data-toggle="modal" data-target="@String.Format("#delete-bank-account-{0}",account.Id)" class="btn btn-danger btn-sm">
                            Delete
                        </a>
                        <a href="#" data-toggle="modal" data-target="@String.Format("#update-bank-account-balance-{0}",account.Id)" class="btn btn-default btn-sm">
                            Update Balance
                        </a>
                        <a role="button" class="btn btn-default btn-sm" data-toggle="collapse" href="@String.Format("#{0}",account.Details.HtmlDivId)" aria-expanded="false" aria-controls="@String.Format("#{0}",account.Details.HtmlDivId)">
                            More
                        </a>
                    </div>
                    <div class="btn-group btn-group-sm">
                        <a href="#" data-toggle="modal" data-target="@String.Format("#add-account-transaction-{0}",account.Id)" class="btn btn-default btn-sm">Add Transaction</a>
                    </div>
                </p>

                <!--Delete Account Modal-->
                <div class="modal fade" id="@String.Format("update-bank-account-balance-{0}",account.Id)" tabindex="-1" role="dialog" aria-labelledby="updateBankAccountBalance">
                    <div class="modal-dialog" role="document">
                        @using (Html.BeginForm("UpdateBalance", "BankAccounts", new { id = account.Id }, FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="confirm-delete-bank-account">Update Balance</h4>
                                </div>
                                <div class="modal-body">
                                    <h3>Are you sure you want to update the balance?</h3>
                                    <p>@account.Name, @account.AccountType, @account.BankName, @account.Owner, @account.Balance</p>
                                    <hr />
                                    @Html.Partial("UpdateBalancePartial", account.BalanceEditor)
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    </div>
                                    <div class="btn-group">
                                        <input type="submit" class="btn btn-primary" role="button" value="Save" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <!--Update Account Balance Modal-->
                <div class="modal fade" id="@String.Format("delete-bank-account-{0}",account.Id)" tabindex="-1" role="dialog" aria-labelledby="deleteBankAccount">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="confirm-delete-bank-account">Confirm</h4>
                            </div>
                            <div class="modal-body">
                                <h3>Are you sure you want to delete this account?</h3>
                                <p>@account.Name, @account.AccountType, @account.BankName, @account.Owner, @account.Balance</p>
                            </div>
                            <div class="modal-footer">
                                @using (Html.BeginForm("Delete", "BankAccounts", new { id = account.Id }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    </div>
                                    <div class="btn-group">
                                        <input type="submit" class="btn btn-danger" role="button" value="Delete" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <!--Bank Account Details Collapse Div-->
                <div class="collapse" id="@account.Details.HtmlDivId">
                    <div class="row">
                        <div class="col-sm-12">
                            @Html.Partial("_BankAccountDetails", @account.Details)
                        </div>
                    </div>
                </div>
                <!--Add Account Transaction Modal-->
                <div class="modal fade" id="@String.Format("add-account-transaction-{0}",account.Id)" tabindex="-1" role="dialog" aria-labelledby="addAccountTransaction">
                    <div class="modal-dialog" role="document">
                        @using (Html.BeginForm("Create", "Transactions", new { id = account.Id }, FormMethod.Post))
                        {
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="confirm-delete-bank-account">Add Transaction</h4>
                                </div>
                                <div class="modal-body">
                                    @Html.Partial("_CreateTransaction", account.TransactionCreator)
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                    </div>
                                    <div class="btn-group">
                                        <input type="submit" class="btn btn-default" role="button" value="Submit" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>

            }
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}