FinancialPortal/Controllers/TransactionsController.cs
using FinancialPortal.Models;
using FinancialPortal.Models.Attributes;
using FinancialPortal.Models.Viewmodels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinancialPortal.Controllers
{
    public class TransactionsController : BaseController
    {
        // POST: Transactions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthTransaction]
        public ActionResult Create(int? id, CreateTransactionViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            else
            {
                if (id != null)
                {
                    var account = db.BankAccounts.Find(id);
                    if (account != null)
                    {
                        account.Transactions.Add(
                            new BankAccountTransaction
                            {
                                Amount = vm.Amount.Amount,
                                Added = DateTimeOffset.Now,
                                CategoryId = vm.CategorySelection,
                                Reconciled = vm.Reconciled,
                                BankAccountId = account.Id,
                                Posted = (vm.Posted.HasValue) ? vm.Posted.Value : vm.Posted
                            });
                        if (vm.Posted.HasValue)
                        {
                            
                        }
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthTransaction]
        public ActionResult Edit(int? id, EditTransactionViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            else
            {
                if (id != null)
                {
                    var transaction = db.BankAccountTransactions.Find(id);
                    if (transaction != null)
                    {
                        transaction.Amount = vm.Amount.Amount;
                        transaction.Posted = (vm.Posted.HasValue) ? vm.Posted.Value : vm.Posted;
                        transaction.CategoryId = vm.CategorySelection;
                        transaction.Reconciled = vm.Reconciled;
                        db.Entry(transaction).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Transactions/Delete/5
        [HttpPost]
        [AuthTransaction]
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var transaction = db.BankAccountTransactions.Find(id);
                if (transaction != null)
                {
                    db.BankAccountTransactions.Remove(transaction);
                    db.Entry(transaction).State = EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

FinancialPortal/Views/Shared/UpdateBalancePartial.cshtml
@model FinancialPortal.Models.Viewmodels.AccountBalanceEditor
<div class="form-group">
    @Html.LabelFor(m => m.BankAccountBalance)<br />
    <div class="input-group">
        <span class="input-group-addon">$</span>
        @Html.EditorFor(m => m.BankAccountBalance, new { htmlAttributes = new
                       {
                           @type = "number",
                           @step = "0.01", @class = "form-control", aria_label = "Account Balance",
                           @placeholder = Model.BankAccountBalance, @value = Model.BankAccountBalance
                       }})
    </div>
    @Html.ValidationMessageFor(m => m.BankAccountBalance, null, new { @class = "text-danger" })
</div>

FinancialPortal/Views/Shared/_BankAccountDetails.cshtml
@model FinancialPortal.Models.Viewmodels.BankAccountDetailsViewModel

<div class="panel panel-default">
    <div class="panel-heading">@Model.BankName</div>
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th colspan="2" class="text-center">
                        Summary
                    </th>
                </tr>
            </thead>
            @foreach (var prop in Model.Properties)
            {
                <tr>
                    <td>
                        @prop.Key
                    </td>
                    <td>
                        @prop.Value
                    </td>
                </tr>
            }
        </table>
        <br />
        @Html.Partial("_Transactions", Model.Transactions)
    </div>
</div>

FinancialPortal/Views/Shared/_CreateTransaction.cshtml
@model FinancialPortal.Models.Viewmodels.CreateTransactionViewModel
@Html.AntiForgeryToken()
<div class="form-group">
    @Html.LabelFor(m => m.Amount.Amount)
    <div class="input-group">
        <span class="input-group-addon">$</span>
        @Html.EditorFor(m => m.Amount.Amount,
         new
         {
             htmlAttributes = new
             {
                 @type = "number",
                 @min = "-999999999.99",
                 @max = "999999999.99",
                 @step = "0.01",
                 @class = "form-control",
                 aria_label = "Account Balance"
             }
         })
    </div>
    @Html.ValidationMessageFor(m => m.Amount.Amount, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Posted)
    @Html.EditorFor(m => m.Posted, new { htmlAttributes = new { @type = "date", @class = "form-control" } })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.CategorySelection)
    @Html.DropDownListFor(m => m.CategorySelection, Model.CategoryList, "", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.CategorySelection, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Reconciled)
    @Html.CheckBoxFor(m => m.Reconciled)
</div>

FinancialPortal/Views/Shared/_EditTransaction.cshtml
@model FinancialPortal.Models.Viewmodels.EditTransactionViewModel
@Html.AntiForgeryToken()
<div class="form-group">
    @Html.LabelFor(m => m.Amount.Amount)
    <div class="input-group">
        <span class="input-group-addon">$</span>
        @Html.EditorFor(m => m.Amount.Amount,
         new
         {
             htmlAttributes = new
             {
                 @type = "number",
                 @min = "-999999999.99",
                 @max = "999999999.99",
                 @step = "0.01",
                 @class = "form-control",
                 aria_label = "Account Balance",
                 @placeholder = Model.Amount.Amount
             }
         })
    </div>
    @Html.ValidationMessageFor(m => m.Amount.Amount, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Posted)
    @Html.EditorFor(m => m.Posted, new { htmlAttributes = new { @type = "date", @class = "form-control" } })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.CategorySelection)
    @Html.DropDownListFor(m => m.CategorySelection, Model.CategoryList, null, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.CategorySelection, "", new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Reconciled)
    @Html.CheckBoxFor(m => m.Reconciled)
</div>
<div class="form-group">
    <input type="submit" role="button" value="Submit" class="btn btn-sm btn-default" />
</div>

FinancialPortal/Views/Shared/_Layout.cshtml
@model FinancialPortal.Models.Viewmodels.BaseViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Budget</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#3fad46">
    <meta name="theme-color" content="#3fad46">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="margin-left:0px">
                    <img alt="Brand" src="~/logo.png" style="height:30px; width:30px; display:inline-block">
                </a>
                @*@Html.ActionLink("Bwright Budgeter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bryan Wright</p>
            <p>Logo created by Oksana Latysheva from the Noun Project</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $('#mark-all-alerts-read').click(function () {
            $.ajax({
                url: '@Url.Action("MarkAllAlertsRead", "Households")',
                async: true,
                dataType: "json"
            }).done(function (response) {
                if (response.message != "ok") {
                    console.log("Something went wrong");
                }
                else {
                    $('#alerts-list a').removeClass('bg-info');
                    $('#alerts-count').text('0');
                }
            })
        });
    </script>
</body>
</html>

FinancialPortal/Views/Shared/_Transactions.cshtml
@model IEnumerable<FinancialPortal.Models.Viewmodels.TransactionViewModel>
<table class="table">
    <thead>
        <tr>
            <th colspan="6" class="text-center">Transactions</th>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(m => m.Amount)</th>
            <th>@Html.DisplayNameFor(m => m.Category)</th>
            <th>@Html.DisplayNameFor(m => m.Added)</th>
            <th>@Html.DisplayNameFor(m => m.Posted)</th>
            <th>@Html.DisplayNameFor(m => m.Reconciled)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var transaction in Model)
        {
            <tr>
                <td>@transaction.Amount</td>
                <td>@transaction.Category</td>
                <td>@transaction.Added</td>
                <td>@transaction.Posted</td>
                <td>@transaction.Reconciled</td>
                <td>
                    <div class="btn-group btn-group-sm">
                        <a role="button" class="btn btn-default btn-sm" data-toggle="collapse" href="@String.Format("#transaction-editor-{0}",transaction.Id)" aria-expanded="false" aria-controls="@String.Format("#transaction-editor-{0}",transaction.Id)">
                            Edit
                        </a>
                        <a href="#" data-toggle="modal" data-target="@String.Format("#delete-transaction-{0}",transaction.Id)" class="btn btn-danger btn-sm">
                            Delete
                        </a>
                    </div>
                    @using (Html.BeginForm("Edit", "Transactions", new { id = transaction.Id }, FormMethod.Post))
                    {
                        <div class="collapse" id="@String.Format("transaction-editor-{0}",transaction.Id)">
                            @Html.Partial("_EditTransaction", transaction.TransactionEditor)
                        </div>
                    }
                    @using (Html.BeginForm("Delete", "Transactions", new { id = transaction.Id }, FormMethod.Post))
                    {
                        <div class="modal fade" id="@String.Format("delete-transaction-{0}",transaction.Id)" tabindex="-1" role="dialog" aria-labelledby="updateBankAccountBalance">
                            <div class="modal-dialog" role="document">
                                @Html.AntiForgeryToken()
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="confirm-delete-bank-account">Delete Transaction</h4>
                                    </div>
                                    <div class="modal-body">
                                        <h3>Are you sure you want to delete this transaction?</h3>
                                        <p>@transaction.Amount</p>
                                        <p>Added @transaction.Added</p>
                                        <p>@transaction.Category</p>
                                        <p>@transaction.Reconciled</p>
                                        <p>@transaction.Posted</p>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        </div>
                                        <div class="btn-group">
                                            <input type="submit" class="btn btn-danger" role="button" value="Delete" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>